# https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support#supported-algorithms
resource "tls_private_key" "sftp_users_keys" {
  for_each = local.sftp_users

  algorithm   = "RSA"
  rsa_bits =  "4096"
}

resource "azapi_resource" "sftp_users" {
  for_each = local.sftp_users

  type = "Microsoft.Storage/storageAccounts/localUsers@2022-09-01"

  name = each.key

  parent_id = data.terraform_remote_state.sftp-storage.outputs.test-sftp-storage-account-id

  body = jsonencode({properties : {
      hasSshKey = true
      # The first container in the `permissions_scopes` list will always be the default home directory
      homeDirectory = ""

      # https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support#container-permissions
      permissionScopes = [
        for scope in each.value.permissions_scopes : {
          service      = "blob"
          resourceName = scope.target_container
          permissions = contains(scope.permissions, "All") ? local.sftp_users_permissions_map["All"] : join("", [
            for permission in distinct(scope.permissions) : local.sftp_users_permissions_map[permission]
          ])
        }
      ]

      sshAuthorizedKeys : [
        {
          key         = tls_private_key.sftp_users_keys[each.key].public_key_openssh
          description = "Automatically generated by Terraform"
        }
        ]
    }
  })

  response_export_values = [
    "id",
    "properties.homeDirectory",
    "properties.permissionScopes",
  ]

  
}

resource "azurerm_key_vault_secret" "sshkey" {
  for_each = local.sftp_users
  name = "private-${each.key}"
  value = tls_private_key.sftp_users_keys[each.key].private_key_pem
  content_type = "Private PEM"
  key_vault_id = "/subscriptions/50a209a2-959f-4cbb-a46a-9d158876e328/resourceGroups/rg-sftp/providers/Microsoft.KeyVault/vaults/bodgedcloud-sftp-kv"
  
}

