variable "sftp_users" {
  description = "List of local SFTP user objects."
  type = list(object({
    name                 = string
    home_directory       = optional(string)
    ssh_key_enabled      = optional(bool, true)
    ssh_password_enabled = optional(bool)
    permissions_scopes = list(object({
      target_container = string
      permissions      = optional(list(string), ["All"])
    }))
    ssh_authorized_keys = optional(list(object({
      key         = string
      description = optional(string)
    })), [])
  }))
  validation {
    condition     = length(var.sftp_users) <= 1000
    error_message = "You can have a maximum of 1000 local users for a storage account."
  }
  validation {
    condition = alltrue([
      for user in var.sftp_users : length(user.permissions_scopes) <= 100
    ])
    error_message = "You can grant each local user access to a maximum of 100 containers."
  }
  validation {
    condition = alltrue([
      for user in var.sftp_users : length(user.ssh_authorized_keys) < 10
    ])
    error_message = "Maximum of 10 public keys per local user (one key is automatically generated by Terraform)."
  }
}

variable "containers" {
  description = "List of objects to create some Blob containers in this Storage Account."
  type = list(object({
    name                  = string
    container_access_type = optional(string)
    metadata              = optional(map(string))
  }))
}